name: Fetch Wikipedia Data

on:
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Update to Python 3.9 or higher

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the data fetch script
      run: |
        python scripts/fetch_wikipedia_data.py

 

